---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: jackson.vector
      vars:
        vector_host_sources:
          test_logs:
            type: file
            include:
              - /var/log/messages
        vector_sinks:
          console:
            type: console
            inputs:
              - journald
              - test_logs
            encoding:
              codec: json
